export const FETCH_CUISINE_LIST_REQUEST = "FETCH_CUISINE_LIST_REQUEST";
export const FETCH_CUISINE_LIST_SUCCESS = "FETCH_CUISINE_LIST_SUCCESS";
export const FETCH_CUISINE_LIST_FAILED = "FETCH_CUISINE_LIST_FAILED";