export const FETCH_BANNER_SINGLE_REQUEST = "FETCH_BANNER_SINGLE_REQUEST";
export const FETCH_BANNER_SINGLE_SUCCESS = "FETCH_BANNER_SINGLE_SUCCESS";
export const FETCH_BANNER_SINGLE_FAILED = "FETCH_BANNER_SINGLE_FAILED";