export const FETCH_SINGLE_MERCHANT_REQUEST = "FETCH_SINGLE_MERCHANT_REQUEST";
export const FETCH_SINGLE_MERCHANT_SUCCESS = "FETCH_SINGLE_MERCHANT_SUCCESS";
export const FETCH_SINGLE_MERCHANT_FAILED = "FETCH_SINGLE_MERCHANT_FAILED";