export const FETCH_WITHDRAWAL_LIST_REQUEST = "FETCH_WITHDRAWAL_LIST_REQUEST";
export const FETCH_WITHDRAWAL_LIST_SUCCESS = "FETCH_WITHDRAWAL_LIST_SUCCESS";
export const FETCH_WITHDRAWAL_LIST_FAILED = "FETCH_WITHDRAWAL_LIST_FAILED";