export const FETCH_SINGLE_BANK_REQUEST = "FETCH_SINGLE_BANK_REQUEST";
export const FETCH_SINGLE_BANK_SUCCESS = "FETCH_SINGLE_BANK_SUCCESS";
export const FETCH_SINGLE_BANK_FAILED = "FETCH_SINGLE_BANK_FAILED";