export const FETCH_ORDER_TIMELINE_REQUEST = "FETCH_TOTAL_REQUEST";
export const FETCH_ORDER_TIMELINE_SUCCESS = "FETCH_ORDER_TIMELINE_SUCCESS";
export const FETCH_ORDER_TIMELINE_FAILED = "FETCH_ORDER_TIMELINE_FAILED";