export const FETCH_DELIVERY_FEE_LIST_REQUEST = "FETCH_DELIVERY_FEE_LIST_REQUEST";
export const FETCH_DELIVERY_FEE_LIST_SUCCESS = "FETCH_DELIVERY_FEE_LIST_SUCCESS";
export const FETCH_DELIVERY_FEE_LIST_FAILED = "FETCH_DELIVERY_FEE_LIST_FAILED";