export const FETCH_CONTACT_LIST_REQUEST = "FETCH_CONTACT_LIST_REQUEST";
export const FETCH_CONTACT_LIST_SUCCESS = "FETCH_CONTACT_LIST_SUCCESS";
export const FETCH_CONTACT_LIST_FAILED = "FETCH_CONTACT_LIST_FAILED";