export const FETCH_MERCHANT_LIST_REQUEST = "FETCH_MERCHANT_LIST_REQUEST";
export const FETCH_MERCHANT_LIST_SUCCESS = "FETCH_MERCHANT_LIST_SUCCESS";
export const FETCH_MERCHANT_LIST_FAILED = "FETCH_MERCHANT_LIST_FAILED";