export const FETCH_FOOD_SINGLE_REQUEST = "FETCH_FOOD_SINGLE_REQUEST";
export const FETCH_FOOD_SINGLE_SUCCESS = "FETCH_FOOD_SINGLE_SUCCESS";
export const FETCH_FOOD_SINGLE_FAILED = "FETCH_FOOD_SINGLE_FAILED";