export const FETCH_COUPON_SINGLE_REQUEST = "FETCH_COUPON_SINGLE_REQUEST";
export const FETCH_COUPON_SINGLE_SUCCESS = "FETCH_COUPON_SINGLE_SUCCESS";
export const FETCH_COUPON_SINGLE_FAILED = "FETCH_COUPON_SINGLE_FAILED";