export const FETCH_BANNER_LIST_REQUEST = "FETCH_BANNER_LIST_REQUEST";
export const FETCH_BANNER_LIST_SUCCESS = "FETCH_BANNER_LIST_SUCCESS";
export const FETCH_BANNER_LIST_FAILED = "FETCH_BANNER_LIST_FAILED";