export const FETCH_COUPON_LIST_REQUEST = "FETCH_COUPON_LIST_REQUEST";
export const FETCH_COUPON_LIST_SUCCESS = "FETCH_COUPON_LIST_SUCCESS";
export const FETCH_COUPON_LIST_FAILED = "FETCH_COUPON_LIST_FAILED";