export const FETCH_TOP_CUISINE_REQUEST = "FETCH_TOP_CUISINE_REQUEST";
export const FETCH_TOP_CUISINE_SUCCESS = "FETCH_TOP_CUISINE_SUCCESS";
export const FETCH_TOP_CUISINE_FAILED = "FETCH_TOP_CUISINE_FAILED";