export const FETCH_ORDER_GROWTH_REQUEST = "FETCH_ORDER_GROWTH_REQUEST";
export const FETCH_ORDER_GROWTH_SUCCESS = "FETCH_ORDER_GROWTH_SUCCESS";
export const FETCH_ORDER_GROWTH_FAILED = "FETCH_ORDER_GROWTH_FAILED";