export const FETCH_CUISINE_SINGLE_REQUEST = "FETCH_CUISINE_SINGLE_REQUEST";
export const FETCH_CUISINE_SINGLE_SUCCESS = "FETCH_CUISINE_SINGLE_SUCCESS";
export const FETCH_CUISINE_SINGLE_FAILED = "FETCH_CUISINE_SINGLE_FAILED";