export const FETCH_TRANSACTION_LIST_REQUEST = "FETCH_TRANSACTION_LIST_REQUEST";
export const FETCH_TRANSACTION_LIST_SUCCESS = "FETCH_TRANSACTION_LIST_SUCCESS";
export const FETCH_TRANSACTION_LIST_FAILED = "FETCH_TRANSACTION_LIST_FAILED";