export const FETCH_SINGLE_STORE_REQUEST = "FETCH_SINGLE_STORE_REQUEST";
export const FETCH_SINGLE_STORE_SUCCESS = "FETCH_SINGLE_STORE_SUCCESS";
export const FETCH_SINGLE_STORE_FAILED = "FETCH_SINGLE_STORE_FAILED";