export const FETCH_SINGLE_MENU_REQUEST = "FETCH_SINGLE_MENU_REQUEST";
export const FETCH_SINGLE_MENU_SUCCESS = "FETCH_SINGLE_MENU_SUCCESS";
export const FETCH_SINGLE_MENU_FAILED = "FETCH_SINGLE_MENU_FAILED";